// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfjOaFiqHNcfSe_JZguM-8gzTyqH5bcBY',
    appId: '1:939277647442:web:c7c6f0630ff82329e5298b',
    messagingSenderId: '939277647442',
    projectId: 'draft1-app-fabao',
    authDomain: 'draft1-app-fabao.firebaseapp.com',
    storageBucket: 'draft1-app-fabao.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoWf_r4rWCkS3ZYaHdONcI5R_OKD-NQa0',
    appId: '1:939277647442:android:25a36c258f63dcbae5298b',
    messagingSenderId: '939277647442',
    projectId: 'draft1-app-fabao',
    storageBucket: 'draft1-app-fabao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGCADewPNiaBdaEBc7A9prJB1MkWJiKKY',
    appId: '1:939277647442:ios:847022429f370efde5298b',
    messagingSenderId: '939277647442',
    projectId: 'draft1-app-fabao',
    storageBucket: 'draft1-app-fabao.firebasestorage.app',
    iosBundleId: 'br.com.fabioalvaro.bank123flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGCADewPNiaBdaEBc7A9prJB1MkWJiKKY',
    appId: '1:939277647442:ios:847022429f370efde5298b',
    messagingSenderId: '939277647442',
    projectId: 'draft1-app-fabao',
    storageBucket: 'draft1-app-fabao.firebasestorage.app',
    iosBundleId: 'br.com.fabioalvaro.bank123flutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfjOaFiqHNcfSe_JZguM-8gzTyqH5bcBY',
    appId: '1:939277647442:web:cfb2cdc6327aedf3e5298b',
    messagingSenderId: '939277647442',
    projectId: 'draft1-app-fabao',
    authDomain: 'draft1-app-fabao.firebaseapp.com',
    storageBucket: 'draft1-app-fabao.firebasestorage.app',
  );

}